
class ThreesError(Exception):
    pass


class InternalError(ThreesError):
    pass
